version: '3'
services:
    oap:
        container_name: oap
        image: apache/skywalking-oap-server:9.7.0
        logging:
            options:
                max-size: "100m"
                max-file: "5"
        restart: always
        ports:
            - "1234:1234"
            - "11800:11800"
            - "12800:12800"

